---
title: "Reproducible Research Course Project 1"
author: "John Goodwin"
date: "May 5, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
To start, download and unzip the data file if it isn't already in your working directory.

```{r}
if (!file.exists('activity.csv')) {
  
  download.file('https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip', 'activity.zip')
  unzip('activity.zip')
  file.remove('activity.zip')
  
}
```

Now read in the activity data.

```{r}
activity <- read_csv('activity.csv',
                     col_types = cols(
                       steps = col_integer(),
                       date = col_date(format = ""),
                       interval = col_integer()
                     ))

```

Now let's do some EDA.

1. What is the mean number of steps taken per day? 

```{r}
daily_tot_steps <- activity %>%
  filter(!is.na(steps)) %>%
  group_by(date) %>%
  summarise(total_steps = sum(steps))
```

```{r}
ggplot(daily_tot_steps, aes(total_steps)) + 
  geom_histogram(bins = 15, fill = 'white', color = 'black') +
  theme_bw() +
  ggtitle('Histogram of Total Steps Per Day')

```

```{r}
mean(daily_tot_steps$total_steps)
median(daily_tot_steps$total_steps)
```

2. What is the average daily activity pattern?

```{r}
int_avg_steps <- activity %>%
  filter(!is.na(steps)) %>%
  group_by(interval) %>%
  summarise(avg_steps = mean(steps))

max_avg <- int_avg_steps %>%
  filter(avg_steps == max(avg_steps))

ggplot(int_avg_steps, aes(interval, avg_steps)) +
  geom_line() +
  theme_bw() +
  geom_vline(data = max_avg, aes(xintercept = interval), color = 'red') +
  ggtitle('Average Steps by Time Interval')
```

3. Impute missing values.

```{r}
activity %>%
  filter(is.na(steps)) %>%
  summarise(na_count = n())
```

